# Generated by Django 3.1.3 on 2020-11-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='movie_movie_title',
        ),
    ]
